Vagrant.configure("2") do | config |
  config.vm.box = "generic/arch"
  config.disksize.size = '20GB'
  config.vm.provider :libvirt do | libvirt |
    libvirt.cpus = 2
    libvirt.memory = 1024
    libvirt.machine_virtual_size = 20
  end

  config.vm.provision "shell", inline: <<-SHELL
    yes | sudo pacman -Syy
    yes | sudo pacman -Su
    yes | sudo pacman -Sy base-devel git
  SHELL
  #config.vm.provision "Basic setup",
  #  type: "shell", path: "setup.sh", privileged: true
  config.vm.synced_folder "./", "/vagrant",
    owner: "vagrant", group: "vagrant", create: true
end
