Vagrant.configure("2") do | config |
  config.vm.box = "fedora/32-cloud-base"
  config.disksize.size = '20GB'
  config.vm.provider :libvirt do | libvirt |
    libvirt.cpus = 2
    libvirt.memory = 1024
  end

  config.vm.provision "shell", inline: <<-SHELL
    yes | sudo dnf upgrade
  SHELL
  config.vm.provision "Basic setup",
    type: "shell", path: "setup.sh", privileged: true
end
