Vagrant.configure('2') do |config|
  config.vm.box = 'kalilinux/rolling'
  config.vm.provider :libvirt do |libvirt|
    libvirt.cpus = 1
    libvirt.memory = 1024
  end

  config.vm.synced_folder './workspace', '/vagrant',
    type: 'nfs',
    mount_options: ['vers=3,tcp']

  config.vm.provision 'shell', path: 'setup-vm.sh'
end
