Vagrant.configure("2") do |config|
  config.vm.box = "kalilinux/rolling"
  config.vm.provider :libvirt do |libvirt|
    libvirt.cpus = 1
    libvirt.memory = 1024
  end

  config.vm.synced_folder ".", "/vagrant",
    type: "rsync",
    rsync__exclude: ".git/",
    rsync__args: ["--verbose", "-z"]
end
