Vagrant.configure("2") do | config |
  config.vm.box = "roboxes/fedora35"
  #config.disksize.size = '20GB'
  config.vm.provider "virtualbox" do |vbox|
    #vbox.gui = true
    vbox.name = "fedora35-dev"
    vbox.memory = 2048
    vbox.cpus = 2
  end

#  config.vm.network "forwarded_port", guest: 22,
#    host: 2222, host_ip: "127.0.0.1"
 
#  config.vm.provision "Basic setup", type: "shell",
#    path: "vagrant/inital_setup.sh", privileged: true
  config.vm.synced_folder "./", "/vagrant"
  config.vm.provision "shell", inline: <<-SHELL
    yes | sudo dnf upgrade
  SHELL
  #config.vm.provision "Basic setup",
  #  type: "shell", path: "setup.sh", privileged: true
end
