Vagrant.configure("2") do |config|
  # Which OS we want
  config.vm.box = "hashicorp/bionic64"

  # How your host sees the VM
  config.vm.provider "virtualbox" do |vbox|
    vbox.name = "bionic64"
    vbox.memory = 2048
    vbox.cpus = 2
  end

  # How setup the network connection
  #config.vm.network "forwarded_port", guest: 80,
  #  host: 8080, host_ip: "127.0.0.1"

  # How you access files from the host
  config.vm.synced_folder "./", "/vagrant"

  # What we want to setup
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt -y upgrade
    sudo apt -y update
  SHELL
end
